name: Build & Run on Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run App on Port 8080 and log output
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "Running $JAR_FILE"
          nohup java -jar "$JAR_FILE" > app.log 2>&1 &
          echo "App started in background. Logs: app.log"

      - name: Show Last 50 Lines of Logs
        run: tail -n 50 app.log
