name: Build & Run on Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Allow PowerShell Script Execution (Windows)
        if: runner.os == 'Windows'
        run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        shell: powershell

      - name: Build Project
        run: mvn clean install -DskipTests
        shell: powershell

      - name: Run App on Port 8080
        run: |
          $jar = Get-ChildItem -Path target -Filter *.jar | Select-Object -First 1
          java -jar $jar.FullName
        shell: powershell
